Repository nimblehq/danger-stylelint, pull requests merged in 2022-05, with the labels that each got.

#1 feature: Create the plugin
  Gemfile.lock
  danger-stylelint.gemspec
  lib/stylelint/plugin.rb
  spec/fixtures/error.json
  spec/fixtures/error.scss
  spec/fixtures/stylelint
  spec/fixtures/valid.json
  spec/fixtures/valid.scss
  spec/stylelint_spec.rb
Labels: type : feature

#3 Release/1.0.0
  Gemfile.lock
  README.md
  danger-stylelint.gemspec
  lib/stylelint/plugin.rb
  spec/fixtures/error.json
  spec/fixtures/error.scss
  spec/fixtures/stylelint
  spec/fixtures/valid.json
  spec/fixtures/valid.scss
  spec/stylelint_spec.rb
Labels: type : release

#4 Prepare for release
  danger-stylelint.gemspec
  lib/stylelint/gem_version.rb
Labels: type : chore
